### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by lloeki** [josa42/svg-preview#22]
I now only rarely use Atom and am looking for a new maintainer for this project. Please chime in.

**Comment by josa42** [comment]
I am interested :smile:

**Comment by lloeki** [comment]
@josa42 great! I'll unpublish the package so that you can take it over and make it point to your fork.

**Comment by josa42** [comment]
@lloeki Cool. You don't need to unpublish, just transfer the repo.

**Comment by lloeki** [comment]
Ah, just unpublished. Anyway, I'll transfer now.

**Comment by lloeki** [comment]
Can't transfer, error'ing because you have a repo in this repo's network. Two solutions:
- I merge your PRs so that you can delete your fork and I can transfer
- your fork becomes the reference (this is what I was setting out to do in the first place)

your choice, @josa42

**Comment by josa42** [comment]
I go with option one.

**Comment by lloeki** [comment]
Ok let's do this.

**Comment by lloeki** [comment]
All merged. Go ahead and zap your fork.

**Comment by josa42** [comment]
My fork is deleted

**Comment by lloeki** [comment]
Transferred.

**Comment by lloeki** [comment]
Thanks. Wishing you smooth sailing!

**Comment by josa42** [comment]
Thanks :wave:
